[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "rules/DivineEngine/Surge/Ruleset/Global.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/LocalAreaNetwork.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/DivineEngine/Surge/Ruleset/Unbreak.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/DivineEngine/Surge/Ruleset/China.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/NobyDa/Surge/Download.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"
